import {
  AIDifficulty,
  AIStyle,
  ContinentId,
  GamePhase,
  GameSettings,
  GameState,
  PlayerType,
  TurnPhase,
} from './game.types';

export const defaultGameSettings: GameSettings = {
  startingMoney: 40000,
  passingStartBonus: 5000,
  maxPlayers: 4,
  enableSound: true,
  gameSpeed: 2,
  enableAuctions: true,
};

export const initialGameState: GameState = {
  id: '',
  phase: GamePhase.SETUP,
  turnPhase: TurnPhase.ROLL_DICE,
  continent: ContinentId.EUROPE,
  board: [],
  players: [
    {
      id: 'player_1',
      name: 'Player 1',
      type: PlayerType.HUMAN,
      avatar: 'lion',
      color: '#f97316',
      money: defaultGameSettings.startingMoney,
      position: 0,
      isInJail: false,
      jailTurns: 0,
      consecutiveDoubles: 0,
      ownedProperties: [],
      isBankrupt: false,
      turnOrder: 0,
    },
    {
      id: 'player_2',
      name: 'AI 1',
      type: PlayerType.AI,
      aiDifficulty: AIDifficulty.BEGINNER,
      aiStyle: AIStyle.CAUTIOUS,
      avatar: 'globe',
      color: '#38bdf8',
      money: defaultGameSettings.startingMoney,
      position: 0,
      isInJail: false,
      jailTurns: 0,
      consecutiveDoubles: 0,
      ownedProperties: [],
      isBankrupt: false,
      turnOrder: 1,
    },
  ],
  currentPlayerIndex: 0,
  settings: defaultGameSettings,
  lastDiceRoll: null,
  turn: 1,
  winner: null,
  activityLog: [],
  auction: {
    propertyPosition: -1,
    active: false,
    highestBid: 0,
    highestBidderId: null,
    minimumBid: 0,
    currentBidderIndex: 0,
    participants: [],
  },
};
